### ISSUE TITLE
Can't get vue-dompurify-html plugin to work in tests

### ISSUE THREAD

**Issue by semiaddict** [vuejs/vue-test-utils-next#1142]
I am trying to test a simple component that uses [vue-dompurify-html](https://github.com/LeSuisse/vue-dompurify-html/tree/vue-next).
If I add vue-dompurify-html as a plugin via the `global` option as described here https://next.vue-test-utils.vuejs.org/migration/#no-more-createlocalvue, I get the following error:

```bash
 TypeError: dompurify is not a function
      at Object.buildDirective (dist/js/webpack:/vue-test-utils--dompurify-html/node_modules/vue-dompurify-html/dist/dompurify-html.js:14:1)
      at Object.install (dist/js/webpack:/vue-test-utils--dompurify-html/node_modules/vue-dompurify-html/dist/index.js:7:1)
      at Object.use (dist/js/webpack:/vue-test-utils--dompurify-html/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3110:1)
      at mount (dist/js/webpack:/vue-test-utils--dompurify-html/node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js:7840:1)
      at shallowMount (dist/js/webpack:/vue-test-utils--dompurify-html/node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js:7911:1)
      at Context.<anonymous> (dist/js/webpack:/vue-test-utils--dompurify-html/tests/unit/example.spec.js:8:1)
```

Here is a simple example:
```js
import { expect } from "chai";
import { shallowMount } from "@vue/test-utils";
import VueDOMPurifyHTML from "vue-dompurify-html";
import App from "@/App.vue";

describe("App.vue", () => {
  it("renders html", () => {
    const wrapper = shallowMount(App, {
      global: {
        plugins: [VueDOMPurifyHTML],
      },
    });
    expect(wrapper.text()).to.include("This is a test");
  });
});
```

And here is a full reproduction example: https://github.com/semiaddict/vue-test-utils--dompurify-html

The App runs just fine with `npm run serve`, but the test fails with the above error.

I have managed to get a bit closer to the source of the issue, but can't figure out if it's due to a missing configuration or something else:  
**When run inside the test, the require statement inside `node_modules/vue-dompurify-html/dist/dompurify-html.js` returns an object with a `default`property containing the function instead of returning the function directly.**

I guess this has to do with a packing config that seems different for the tests than the build.
Any idea of how to solve this ?

**Comment by cexbrayat** [comment]
Hi @semiaddict 

I don't think this is an issue with VTU to be honest, probably more a configuration error or an issue with the plugin.
You should probably ask the plugin authors, as they may know how to use it in tests, or can point you to some documentation or similar issues. A super quick search shows issues with similar problems already on their Github repo.

If it ends up being a real problem with VTU, ping me so I can reopen the issue
