### ISSUE TITLE
Bug: for-of loop of Map not working

### ISSUE THREAD

**Issue by architshin** [vuejs/vue-test-utils-next#1236]
**Describe the bug**

Map iteration using for-of loop inside computed() does't work. 
Same issue as #1222.

**To Reproduce**

[Reproduction repo](https://github.com/architshin/issue-vuetestutils-maploop)

`App.vue`
``` vue
<template>
    <p>Total points(forEach): {{totalPointsByForEach}}</p>
    <p>Total points(for-of): {{totalPointsByForOf}}</p>
</template>

<script lang="ts">
import {defineComponent, ref, computed} from "vue";

export default defineComponent({
    name: "App",
    setup() {
        const memberListInit = new Map<number, Member>();
        memberListInit.set(33456, {id: 33456, points: 35});
        memberListInit.set(47783, {id: 47783, points: 53});
        const memberList = ref(memberListInit);
        const totalPointsByForEach = computed(
            (): number => {
                let total = 0;
                memberList.value.forEach(
                    (member: Member, id: number): void => {
                        total += member.points;
                    }
                );
                return total;
            }
        );
        const totalPointsByForOf = computed(
            (): number => {
                let total = 0;
                for(const member of memberList.value.values()) {
                        total += member.points;
                }
                return total;
            }
        );
        return {
            memberList,
            totalPointsByForEach,
            totalPointsByForOf
        }
    }
});

interface Member {
    id: number;
    points: number;
}
</script>
```
`App.spec.ts`
```ts
import {mount} from "@vue/test-utils";
import App from "@/App.vue";

describe(
    "Tests of App.vue",
    () => {
        test(
            "a test of total points",
            () => {
                const wrapper = mount(App);
                const actualHTML = wrapper.html();
                const expectedForEach = "Total points(forEach): 88";
                const expectedForOf = "Total points(for-of): 88";
                expect(actualHTML).toContain(expectedForEach);
                expect(actualHTML).toContain(expectedForOf);
            }
        );
    }
);
```
`result`
```
> issue-vuetestutils-maploop@0.1.0 test:unit
> vue-cli-service test:unit "tests/unit/App.spec.ts"

 FAIL  tests/unit/App.spec.ts
  Tests of App.vue
    ✕ a test of total points (18 ms)

  ● Tests of App.vue › a test of total points

    expect(received).toContain(expected) // indexOf

    Expected substring: "Total points(for-of): 88"
    Received string:    "<p>Total points(forEach): 88</p>
    <p>Total points(for-of): 0</p>"

      13 |                              const expectedForOf = "Total points(for-of): 88";
      14 |                              expect(actualHTML).toContain(expectedForEach);
    > 15 |                              expect(actualHTML).toContain(expectedForOf);
         |                                                 ^
      16 |                      }
      17 |              );
      18 |      }

      at Object.<anonymous> (tests/unit/App.spec.ts:15:24)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.756 s, estimated 2 s
Ran all test suites matching /tests\/unit\/App.spec.ts/i.
```
This is not the case when using pure TS functions.
`functions.ts`
```ts
interface Member {
    id: number;
    points: number;
}

const memberList = new Map<number, Member>();
memberList.set(33456, {id: 33456, points: 35});
memberList.set(47783, {id: 47783, points: 53});

export function getTotalPointsByForEach(): number {
    let total = 0;
    memberList.forEach(
        (member: Member, id: number): void => {
            total += member.points;
        }
    );
    return total;
}

export function getTotalPointsByForOf(): number {
    let total = 0;
    for(const member of memberList.values()) {
        total += member.points;
    }
    return total;
}
```
`functions.spec.ts`
```ts
import {getTotalPointsByForEach, getTotalPointsByForOf} from "@/functions";

describe(
    "tests of functions",
    () => {
        test(
            "a test of getTotalPointsByForEach",
            () => {
                const actual = getTotalPointsByForEach();
                const expected = 88;
                expect(actual).toBe(expected);
            }
        );
        test(
            "a test of getTotalPointsByForOf",
            () => {
                const actual = getTotalPointsByForOf();
                const expected = 88;
                expect(actual).toBe(expected);
            }
        );
    }
);
```
`result`
```
> issue-vuetestutils-maploop@0.1.0 test:unit
> vue-cli-service test:unit "tests/unit/functions.spec.ts"

 PASS  tests/unit/functions.spec.ts
  tests of functions
    ✓ a test of getTotalPointsByForEach (1 ms)
    ✓ a test of getTotalPointsByForOf

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.203 s
Ran all test suites matching /tests\/unit\/functions.spec.ts/i.
```

**Expected behavior**

`Tests of App.vue › a test of total points` test should pass.

**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.18
- `Vue` version: 3.2.26
- `node` version: 16.13.2:
- `npm` version: 8.1.2:

**Additional context**

**Comment by lmiller1990** [comment]
This is so strange. It works fine in the browser. I did

```ts
		const totalPointsByForOf = computed(
			(): number => {
				let total = 0;
				for(const member of Array.from(memberList.value.values())) {
						total += member.points;
				}
				return total;
			}
		);
```

and using `Array.from` works. We do nothing special inside of Test Utils for `Map`, or anything for the reactivity system - I have no idea what's going on here!

**Comment by lmiller1990** [comment]
```js
const { computed, ref } = require("vue");
const memberListInit = new Map();

memberListInit.set(33456, { id: 33456, points: 35 });
memberListInit.set(47783, { id: 47783, points: 53 });
const memberList = ref(memberListInit);

const totalPointsByForOf = computed(() => {
  let total = 0;
  for (const member of Array.from(memberList.value.values())) {
    total += member.points;
  }
  return total;
});

console.log(totalPointsByForOf.value) //=> 88
```

Working fine - seems like a problem in either Test Utils, or Vue Jest...

**Comment by lmiller1990** [comment]
```ts
require('jsdom-global')()
global.SVGElement = window.SVGElement;

const { ref, computed, h } = require('vue')
const { mount } = require('@vue/test-utils')

const w = mount({
  setup() {
    const memberListInit = new Map();

    memberListInit.set(33456, { id: 33456, points: 35 });
    memberListInit.set(47783, { id: 47783, points: 53 });
    const memberList = ref(memberListInit);

    const totalPointsByForOf = computed(() => {
      let total = 0;
      for (const member of Array.from(memberList.value.values())) {
        total += member.points;
      }
      return total;
    });

    return () => h("div", totalPointsByForOf.value);
  },
});

console.log(w.html()) //#=> <div>88</div>
```

Run with `node repro.js` works fine -- bug is either in Jest, Vue Jest, or something else.

**Comment by lmiller1990** [comment]
I added the latest `@vue/vue3-jest`, it works fine now. `"@vue/vue3-jest": "^27.0.0-alpha.4"`.

Please try that - let me know if you have any problems still.
