### ISSUE TITLE
Unmount on multi-root component causes JSDOM error

### ISSUE THREAD

**Issue by JeremyWuuuuu** [vuejs/vue-test-utils-next#181]
## Subject of the issue
Unmount on multi-root component causes JSDOM throwing error `NotFoundError: The object can not be found here.`

## Environment
OS:  macOS Catalina 10.15.1
Node: 12.18.3
JSDOM: 11.12.0
Jest: 24.9.0
"@vue/testing-utils": 2.0.0-beta.0

## Steps to reproduce
```vue
import { mount } from '@vue/test-utils'

const AXIOM = 'Rem is the best girl'
const TRIGGER = 'trigger'
const OTHER_CLASS = 'other-class'
const Component = {
  template: `
    <div class="${OTHER_CLASS}">Hello</div>
    <div class="${TRIGGER}">${AXIOM}</div>
  `
}

describe("this causes error'", () => {
  it("causes error", () => {
    const wrapper = mount(Component)
    wrapper.unmount() // throws NotFoundError: The object can not be found here.
  })
})
```
## Expected behavior
Unmount correctly

## Actual behavior
```js
 NotFoundError: The object can not be found here.

      14 |   it("causes error", () => {
      15 |     const wrapper = mount(Component)
    > 16 |     wrapper.unmount() // throws NotFoundError: The object can not be found here.
         | ^
      17 |   })
      18 | })

      at HTMLDivElementImpl.removeChild (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:299:13)
      at HTMLDivElement.removeChild (node_modules/jsdom/lib/jsdom/living/generated/Node.js:326:45)
      at VueWrapper.Object.<anonymous>.VueWrapper.unmount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:1946:32)
      at Object.<anonymous> (packages/directives/__tests__/directives.spec.ts:16:1)
```

**Comment by JeremyWuuuuu** [comment]
And after I added a root node for the `Component` this error no longer appears

**Comment by lmiller1990** [comment]
I wonder if this extra logic we have needs to be amended to consider the fragment use case. I'd say so.

https://github.com/vuejs/vue-test-utils-next/blob/e5aee88ec6437a7d28dd0a4a9d0e84bbe3a8df40/src/vueWrapper.ts#L219

Are you interested in making a PR?

**Comment by JeremyWuuuuu** [comment]
> vue-test-utils-next/src/vueWrapper.ts

Sure, I'll make a PR for this bug

**Comment by lmiller1990** [comment]
Great, even if you cannot figure the bug a PR w/ a test reproducing it would help a lot too! Thanks!

**Comment by JeremyWuuuuu** [comment]
Link PR here #182
