### ISSUE TITLE
Warnings and error "There was no ChunkGraph assigned to the Module for backward-compat" when using with default test in vue 2 project with webpack 5

### ISSUE THREAD

**Issue by sceee** [vuejs/vue-test-utils-next#343]
I'm using the following versions
* @vue/cli 5.0.0-alpha.3
* @vue/test-utils 2.0.0-rc.0
* vue 2.6.12
* webpack 5.19.0

and I tried to execute the default example unit test:

```
import { expect } from 'chai'
import { shallowMount } from '@vue/test-utils'
import HelloWorld from '@/components/HelloWorld.vue'

describe('HelloWorld.vue', () => {
  it('renders props.msg when passed', () => {
    const msg = 'new message'
    const wrapper = shallowMount(HelloWorld, {
      propsData: { msg }
    })
    expect(wrapper.text()).to.include(msg)
  })
})


```

Unfortunately, it gives me the following warnings and error when executing `vue-cli-service test:unit`:
```
> vue-cli-service test:unit

  [                         ] 0% () WEBPACK  Compiling...

  [=======================  ] 92% (sealing)(node:22544) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
  [=========================] 98% (emitting)

 WARNING  Compiled with 11 warnings

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'nextTick' (imported as 'nextTick') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'setDevtoolsHook' (imported as 'setDevtoolsHook') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'getCurrentInstance' (imported as 'getCurrentInstance') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'h' (imported as 'h') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'defineComponent' (imported as 'defineComponent') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'transformVNodeArgs' (imported as 'transformVNodeArgs') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'Transition' (imported as 'Transition') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'TransitionGroup' (imported as 'TransitionGroup') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'reactive' (imported as 'reactive') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

export 'createApp' (imported as 'createApp') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/mochapack/lib/entry.js

Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "\"../../../tests/unit/example.spec.ts\""

  [=========================] 99% (done) WEBPACK  Compiled with 23 warning(s)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'nextTick' (imported as 'nextTick') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'setDevtoolsHook' (imported as 'setDevtoolsHook') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'nextTick' (imported as 'nextTick') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'nextTick' (imported as 'nextTick') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'getCurrentInstance' (imported as 'getCurrentInstance') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'getCurrentInstance' (imported as 'getCurrentInstance') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'h' (imported as 'h') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'defineComponent' (imported as 'defineComponent') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'h' (imported as 'h') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'defineComponent' (imported as 'defineComponent') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'transformVNodeArgs' (imported as 'transformVNodeArgs') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'Transition' (imported as 'Transition') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'TransitionGroup' (imported as 'TransitionGroup') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'defineComponent' (imported as 'defineComponent') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'h' (imported as 'h') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'h' (imported as 'h') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'reactive' (imported as 'reactive') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'defineComponent' (imported as 'defineComponent') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'h' (imported as 'h') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'createApp' (imported as 'createApp') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'defineComponent' (imported as 'defineComponent') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js

  export 'h' (imported as 'h') was not found in 'vue' (possible exports: default)

Warning in ./node_modules/mochapack/lib/entry.js

  Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
  Invalid dependencies may lead to broken watching and caching.
  As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
  Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
  Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
  Globs: They are not supported. Pass absolute path to the directory as context dependencies.
  The following invalid values have been reported:
   * "\"../../../tests/unit/example.spec.ts\""

  [=========================] 100% (completed)

(node:22544) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.modules was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:22544) [DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API
Error: Module.id: There was no ChunkGraph assigned to the Module for backward-compat (Use the new API)
    at C:\tmp\unittestbugrep\node_modules\webpack\lib\ChunkGraph.js:1474:12
    at deprecated (internal/util.js:89:15)
    at Function.getChunkGraphForModule (C:\tmp\unittestbugrep\node_modules\webpack\lib\ChunkGraph.js:1465:18)
    at MakeNamespaceObjectRuntimeModule.get id [as id] (C:\tmp\unittestbugrep\node_modules\webpack\lib\Module.js:169:21)
    at C:\tmp\unittestbugrep\node_modules\mochapack\src\webpack\util\getAffectedModuleIds.ts:43:51
    at Array.reduce (<anonymous>)
    at Set.set.<computed> [as reduce] (C:\tmp\unittestbugrep\node_modules\webpack\lib\util\deprecation.js:87:35)
    at buildModuleMap (C:\tmp\unittestbugrep\node_modules\mochapack\src\webpack\util\getAffectedModuleIds.ts:42:29)
    at Object.getAffectedModuleIds [as default] (C:\tmp\unittestbugrep\node_modules\mochapack\src\webpack\util\getAffectedModuleIds.ts:144:32)
    at Object.getBuildStats [as default] (C:\tmp\unittestbugrep\node_modules\mochapack\src\webpack\util\getBuildStats.ts:20:47)
    at TestRunner.prepareMocha (C:\tmp\unittestbugrep\node_modules\mochapack\src\runner\TestRunner.ts:76:49)
    at C:\tmp\unittestbugrep\node_modules\mochapack\src\runner\TestRunner.ts:116:34
    at C:\tmp\unittestbugrep\node_modules\mochapack\src\webpack\compiler\registerReadyCallback.ts:15:7
    at Hook.eval [as callAsync] (eval at create (C:\tmp\unittestbugrep\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:60:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\tmp\unittestbugrep\node_modules\tapable\lib\Hook.js:18:14)
    at C:\tmp\unittestbugrep\node_modules\webpack\lib\Compiler.js:447:23
 ERROR  Error: mochapack exited with code 1.
Error: mochapack exited with code 1.
    at ChildProcess.<anonymous> (C:\tmp\unittestbugrep\node_modules\@vue\cli-plugin-unit-mocha\index.js:84:18)
    at ChildProcess.emit (events.js:326:22)
    at ChildProcess.cp.emit (C:\tmp\unittestbugrep\node_modules\cross-spawn\lib\enoent.js:34:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

I am not really sure whether this really fits here, though. Sorry if it does not.
When using `webpack@4`, it works.

**Comment by cexbrayat** [comment]
Hi there! 

Vue Test Utils v2 is to be used with Vue 3, and does not work with Vue 2.
Please use VTU v1 if you work with Vue 2 ;)
