### ISSUE TITLE
shallowMount fails for script setup components

### ISSUE THREAD

**Issue by rrittwag** [vuejs/vue-test-utils-next#357]
**Description**
I converted all my project's components to the new experimental "script setup" syntax. The project runs and builds smoothly. But tests containing shallowMounted components fail with a TypeError:

```
TypeError: Cannot read property 'replace' of undefined
    at node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:1781:16
    at node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:1776:37
    at matchName (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:1792:21)
    at resolveComponentStubByName (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2159:13)
    at node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2230:24
    at createVNodeWithArgsTransform (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5223:11)
    at Proxy.render (src/ExampleWithoutScript.vue:37:110)
    at renderComponentRoot (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:707:44)
    at componentEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4158:53)
    at reactiveEffect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:46:24)
    at Object.effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:21:9)
    at setupRenderEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4141:38)
    at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4099:9)
    at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4059:17)
    at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3687:21)
    at componentEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4176:21)
    at reactiveEffect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:46:24)
    at Object.effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:21:9)
    at setupRenderEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4141:38)
    at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4099:9)
    at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4059:17)
    at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3687:21)
    at render (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4759:13)
    at mount (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3028:25)
    at Object.app.mount (node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1220:23)
    at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2426:18)
    at shallowMount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2441:12)
    at Object.<anonymous> (tests/unit/ExampleWithoutScript.spec.js:6:21)

```
**Version**: 2.0.0-rc.0

**Comment by rrittwag** [comment]
I provided PR #358, that fixes the bug and adds examples in unit tests.

**Comment by lmiller1990** [comment]
Afaik `name` is not supported in script setup. It probably should be, maybe we can ask about it in the RFC. Something like `<script setup name="...">`.

Great fix, lgtm!

**Comment by lmiller1990** [comment]
Will release on the weekend! Please wait a little. There is some other PRs to review/merge.
