### ISSUE TITLE
ReferenceError: SVGElement is not defined, weird behavior with different Vue versions 

### ISSUE THREAD

**Issue by setaman** [vuejs/vue-test-utils-next#556]
Hi, I am the developer of [this](https://github.com/setaman/vue-ellipse-progress) library and trying to migrate my tests to v2. However I encounter very confusing behavior with different Vue versions. Especially in the combination `2.0.0-rc.6` and Vue `3.0.11` I get the following error while trying to run my tests:
```
ReferenceError: SVGElement is not defined
    at Object.app.mount (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:1259:1)
    at mount (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js:7891:1)
    at factory (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/tests/unit/container.spec.js:10:1)
    at Suite.<anonymous> (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/tests/unit/container.spec.js:36:1)
    at Object.create (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Suite.<anonymous> (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/tests/unit/container.spec.js:34:1)
    at Object.create (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object../tests/unit/container.spec.js (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/tests/unit/container.spec.js:33:1)
    at __webpack_require__ (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/webpack/bootstrap:19:1)
    at run (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/node_modules/mochapack/lib/entry.js:3:1)
    at Array.forEach (<anonymous>)
    at Object../node_modules/mochapack/lib/entry.js (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/node_modules/mochapack/lib/entry.js:10:1)
    at __webpack_require__ (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/webpack/bootstrap:19:1)
    at /home/serg/Documents/Projects/vue-ellipse-progress/dist/js/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/serg/Documents/Projects/vue-ellipse-progress/dist/js/main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.module_1.default._extensions.<computed> [as .js] (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mochapack/src/util/registerRequireHook.ts:106:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mocha/lib/mocha.js:809:10)
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mochapack/src/runner/TestRunner.ts:105:23
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/mochapack/src/webpack/compiler/registerReadyCallback.ts:14:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at AsyncSeriesHook.lazyCompileHook (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/tapable/lib/Hook.js:154:20)
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/webpack/lib/Compiler.js:298:10
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/webpack/lib/Compiler.js:485:14
    at eval (eval at create (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/copy-webpack-plugin/dist/index.js:115:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/tapable/lib/Hook.js:154:20)
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/webpack/lib/Compiler.js:482:27
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/neo-async/async.js:2818:7
    at done (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /home/serg/Documents/Projects/vue-ellipse-progress/node_modules/webpack/lib/Compiler.js:464:33
    at MemoryFileSystem.writeFile (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/webpack/lib/Compiler.js:462:30)
    at Immediate._onImmediate (/home/serg/Documents/Projects/vue-ellipse-progress/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at processImmediate (internal/timers.js:461:21)
```

I have tried different versions combinations and have noticed strange things. The tests run as expected with Vue `3.0.6 - 3.0.7` but with `3.0.8 - 3.0.11` i get the error, same with `3.0.5`.

## How to reproduce
Clone the [repo](https://github.com/setaman/vue-ellipse-progress) and run in the [v2-unit-test](https://github.com/setaman/vue-ellipse-progress/tree/v2-unit-test) branch with Node.js 14.16:
```
npm i
npm run test
```

**Comment by cexbrayat** [comment]
Hi @setaman , thanks for opening an issue

I think this is unrelated to VTU. The same concern has been raised in the vue-next repo: see https://github.com/vuejs/vue-next/issues/3590 and other related issues. 

I'll let you track these issues and I'm going to close this one.

**Comment by setaman** [comment]
Hi @cexbrayat,
thanks, i see, the issues are coming now.
