### ISSUE TITLE
Props are not added to instance when calling mount() in simple example

### ISSUE THREAD

**Issue by elliottregan** [vuejs/vue-test-utils-next#579]
I built a simple demo based on the documentation's example. Data properties get rendered correctly, but any Props get dropped.

In the console, I get these errors:

```
  console.warn
    [Vue warn]: Property "count" was accessed during render but is not defined on instance. 
      at <Anonymous count=5 ref="VTU_COMPONENT" > 
      at <VTUROOT>



      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40:17)
      at Object.get (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6215:17)
      at Proxy.render (src/components/HelloWorld.vue:35:85)
      at renderComponentRoot (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:843:44)
      at componentEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4242:53)
      at reactiveEffect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:46:24)
      at Object.effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:21:9)

  console.warn
    [Vue warn]: Extraneous non-props attributes (count) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
      at <Anonymous count=5 ref="VTU_COMPONENT" > 
      at <VTUROOT>

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40:17)
      at renderComponentRoot (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:914:25)
      at componentEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4242:53)
      at reactiveEffect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:46:24)
      at Object.effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:21:9)
      at setupRenderEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4225:38)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4184:9)
```

If I log the imported Vue component (before calling mount), I see the props as 
```js
// console.log(HelloWorld)
    {
      default: {
        props: { count: [Object] },
        data: [Function: data],
        render: [Function: render]
      },
      render: [Function: render]
    }
```

## Test file
```js

import { mount } from '@vue/test-utils'

import HelloWorld from '../../src/components/HelloWorld.vue'

describe('HelloWorld.vue', () => {
  it('renders a greeting', () => {
    const wrapper = mount(HelloWorld, {
      data() {
        return {
          message: 'world'
        }
      }
    })
  
    expect(wrapper.html()).toContain('Hello world')
  })
  it('renders a count', () => {
    const wrapper = mount(HelloWorld, {
      props: {
        count: 5
      },
      data() {
        return {
          message: 'world'
        }
      }
    })
  
    expect(wrapper.html()).toContain('Count: 5')
  })
})
```

## Vue Component
```vue
<template>
  <div>Hello {{ message }}</div>
  <span>Count: {{ count }}</span>
</template>

<script>
export default {
  props: {
    count: {
      type: Number,
      required: true
    }
  },
  data() {
    return {
      message: 'everyone'
    }
  }
}
</script>
```

I can add more details here, but the full project with the broken test examples can be found here: https://github.com/elliottregan/vite-vue-starter/tree/jest

If you have Docker installed, you should be able to just run `make dev-test`, and you'll see the output.

**Comment by elliottregan** [comment]
Ok, the issue is due to using the `.mjs` extension for my test files. 

If I include `babel-jest` in my transforms, and remove the `.mjs` extension, my tests run as expected. 

```js
// jest.config.js
{
  ...
  transform: {
    '^.+\\.vue$': 'vue-jest',
    '^.+\\js$': 'babel-jest'
  },
}
```

If this is a scenario you're interested in exploring, I can open a PR. Seems like a fair requirement to include Babel for the time-being, though.
