### ISSUE TITLE
Cannot read property 'addEventListener' of null if setup returns a promise

### ISSUE THREAD

**Issue by Nowadays** [vuejs/vue-test-utils-next#584]
Using vue 3.0.11 and @vue/test-utils 2.0.0-rc.6

In a Jest environment, if the component you're testing has a `setup` function marked as async, the following error happens when mounting: 

```
TypeError: Cannot read property 'addEventListener' of null

    at _loop_1 (/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7436:21)
    at VueWrapper.Object.<anonymous>.VueWrapper.attachNativeEventListener (/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7446:13)
    at new VueWrapper (/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7397:15)
    at createWrapper (/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7573:12)
    at mount (/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7932:12)
    at shallowMount (/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7935:12)
```

I tried refactoring using the lifecycle hooks to remove the need of `await` in the setup function, however the render fails because the object is undefined, using a simplified example:

The template:
```
<template>
  <div class="container max-w-3xl mx-auto pb-16 sm:p-3 sm:pb-16">
    <!-- Header -->
    <div class="mx-auto flex items-center justify-between px-3 py-4 mb-2 sm:px-5 sm:py-8 sm:mb-4 border-b">
      <h2 class="text-xl sm:text-2xl font-light text-gray-800">
        Souscription
        <span class="uppercase">{{ souscription.reference }}</span>
      </h2>
      <button id="retour" class="border-button" @click="$router.back()">Retour</button>
    </div>
</template>
```

The setup function:

```
export default defineComponent({
  name: 'SouscriptionDetail',
  setup(): unknown {
    const route = useRoute();
    const {
      souscription,
      fetchSouscription,
    } = useSouscription();

    onMounted(async () => {
      await fetchSouscription(route.params.id);
    });

    return {
      souscription,
    };
  },
});

```

Where `souscription` and `fetchSouscription` are defined as follow:

```
export function useSouscription(): any {
  const souscription = ref<Souscription>();

  async function fetchSouscription(uuid: string): Promise<void> {
    try {
      souscription.value = await getSouscription(uuid); // an HTTP GET using axios
    } catch (e) {
      logger.error('Unable to fetch Souscriptions', e);
    }
  }

  return {
    fetchSouscription,
    souscription,
  };
}
```

When mounting the component I get the following: `TypeError: Cannot read property 'reference' of undefined`

I'm quite new to the composition API so I must have misunderstood the doc at some point

**Comment by Nowadays** [comment]
@cexbrayat Opened a PR with both errors reproduced in tests: https://github.com/vuejs/vue-test-utils-next/pull/585

**Comment by cexbrayat** [comment]
Thanks I see what's going on now.

For the async setup: you can't mount the component directly, you have to wrap it in a Suspense. Something like:

```ts
const AsyncWrapper = defineComponent({
template: '<Suspense><Issue584Async></Issue584Async></Suspense>',
components: {
  Issue584Async
}
})
const wrapper = mount(AsyncWrapper});
```

For the sync setup: I think the error is pretty normal as you don't initialiaze `souscription`.
Change it to `const souscription = ref({ reference: '' });` and the error will go away
