### ISSUE TITLE
I cannot resolve problems on mount (document is 'undefiend' at @vue/runtime-dom -> doc is null)

### ISSUE THREAD

**Issue by TIGrannet** [vuejs/vue-test-utils-next#827]
Hello. I came from Japan.

I'm trying @vue/test-utils on Laravel8 with laravel-mix.
I'll try to test tests/Javascript/example.spec.js by `npm run test`.

```example.spec.js
import expect from 'expect';
import { mount } from '@vue/test-utils';

describe('Hello', () => {
    it('say that it is an example components', () => {
        const Component = {
            template: '<div>Hello World</div>'
        }
        let wrapper = mount(Component);
        expect(wrapper.text()).toContain('Hello World');
    });
});
```

But it causes TypeError on @vue/runtime-dom/dist/runtime-dom.cjs.js.

```
  Hello
    1) say that it is an example components


  0 passing (74ms)
  1 failing

  1) Hello
       say that it is an example components:
     TypeError: Cannot read property 'createElementNS' of null
      at createElement (node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:23:19)
      at mountElement (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4738:29)
      at processElement (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4727:13)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4647:21)
      at componentEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5170:21)
      at reactiveEffect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:46:24)
      at Object.effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:21:9)
      at setupRenderEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5116:38)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5075:9)
      at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5033:17)

 MOCHA  Tests completed with 1 failure(s)
```

I checked @vue/test-util, mockapack, mocha-loader, and some web article, but I cannot resolve that problem.
I thought source of ploblem is "load timing of runtime-dom.cjs.js". It assigned null to reciever of createElementNS on loaded.
I hope to delay the timing of load runtime-dom.cjs.js.

Do you have any idea?

My environment is here:
```
OS: Linux on Docker
Nginx v1.21.1
php v8.0.9(php-fpm)
Node.js v16.6.0
MySQL v8.0.26
```

I'll show tests/Javascript/setupjs and webpack.mix.js, package.json.

```setup.js
require('jsdom-global')();

global.expect = require('expect')
global.SVGElement = global.Element
```

```webpack.mix.js
const mix = require('laravel-mix');
const nodeExternals = require('webpack-node-externals');
mix.js('./resources/js/app.js', './public/js').
    sass('resources/sass/app.scss', 'public/css').
    vue().
    webpackConfig({
        target: 'node',
        resolve: {
            fallback: {
                stream: require.resolve("stream-browserify"),
                constants: require.resolve("constants-browserify"),
                path: require.resolve("path-browserify")
            },
            mainFields: ["main", "module"]
        },
        devtool: "source-map",
        externals: [nodeExternals({})]
    });
```

```package.json
{
    "private": true,
    "scripts": {
        :
        "test": "node_modules/mochapack/bin/mochapack --mode=development --webpack-config=node_modules/laravel-mix/setup/webpack.config.js --require tests/Javascript/setup.js tests/Javascript/**/*.spec.js"
    },
    "devDependencies": {
        "@types/webpack-env": "^1.16.2",
        "@vue/compiler-sfc": "^3.1.5",
        "@vue/server-renderer": "^3.1.5",
        "@vue/test-utils": "^2.0.0-rc.11",
        "axios": "^0.21",
        "bootstrap": "^4.6.0",
        "constants-browserify": "^1.0.0",
        "cross-env": "^7.0.3",
        "expect": "^27.0.6",
        "jquery": "^3.6",
        "jsdom": "^16.7.0",
        "jsdom-global": "^3.0.2",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "mocha": "^8.4.0",
        "mocha-loader": "^5.1.5",
        "mochapack": "^2.1.2",
        "path-browserify": "^1.0.1",
        "popper.js": "^1.16.1",
        "postcss": "^8.1.14",
        "resolve-url-loader": "^3.1.2",
        "sass": "^1.32.11",
        "sass-loader": "^12.1.0",
        "stream-browserify": "^3.0.0",
        "style-loader": "^3.2.1",
        "vue": "^3.1.5",
        "vue-loader": "^16.4.1",
        "vue-style-loader": "^4.1.3",
        "webpack-node-externals": "^3.0.0"
    }
}
```

**Comment by standbyoneself** [comment]
Share a repo please. It is too difficult to figure it out what exactly causes the error

**Comment by TIGrannet** [comment]
Thanks for reply!

We have prepared a repository here that reproduces the problem.
https://github.com/TIGrannet/Vue_and_Laravel_for_share

on terminal:
```
docker-compose up -d
docker-compose exec node ash
```

on node container terminal:
```
cd /var/www/laravel1
npm install
npm run dev
npm run test
```

Result is blow:
```
Hello
    1) say that it is an example components


  0 passing (66ms)
  1 failing

  1) Hello
       say that it is an example components:
     TypeError: Cannot read property 'createElementNS' of null
      at createElement (node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:23:19)
      at mountElement (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4037:29)
      at processElement (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4026:13)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3946:21)
      at ReactiveEffect.componentUpdateFn [as fn] (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4482:21)
      at ReactiveEffect.run (node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)
      at setupRenderEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4600:9)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4386:9)
      at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4344:17)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3949:21)



 MOCHA  Tests completed with 1 failure(s)
```

Thank you.

**Comment by standbyoneself** [comment]
@TIGrannet You **should** specify the version of `Vue` in your `webpack.mix.js`.

As Laravel docs say:
> The necessary webpack configuration for Vue differs slightly dependent on whether you're using Vue 2 or 3. Mix will do its best to automatically identify which version you have installed and proceed accordingly. However, you can also explicity set your desired Vue version.

So change `vue()` to `vue({ version: 3 })` and your tests will pass

**Comment by TIGrannet** [comment]
The test passed without any problems. Thank you very much.
