### ISSUE TITLE
Vue3 with vite error: Cannot destructure property 'config' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by lampewebdev** [vuejs/vue-test-utils-next#973]
I'm getting the following error, then I'm trying to run jest in a vite project.
I'm not sure what I'm doing wrong.

```bash
➜ pnpm exec jest
 FAIL  tests/unit/TpFlag.spec.ts
  ● Test suite failed to run

    TypeError: Cannot destructure property 'config' of 'undefined' as it is undefined.

      at Object.getCacheKey (node_modules/.pnpm/vue-jest@5.0.0-alpha.10_44e998dd56eb885d0c861c97bb8b7d64/node_modules/vue-jest/lib/index.js:10:7)
      at ScriptTransformer._getCacheKey (node_modules/.pnpm/@jest+transform@27.2.1/node_modules/@jest/transform/build/ScriptTransformer.js:280:41)
      at ScriptTransformer._getFileCachePath (node_modules/.pnpm/@jest+transform@27.2.1/node_modules/@jest/transform/build/ScriptTransformer.js:351:27)
      at ScriptTransformer.transformSource (node_modules/.pnpm/@jest+transform@27.2.1/node_modules/@jest/transform/build/ScriptTransformer.js:588:32)
      at ScriptTransformer._transformAndBuildScript (node_modules/.pnpm/@jest+transform@27.2.1/node_modules/@jest/transform/build/ScriptTransformer.js:758:40)
      at ScriptTransformer.transform (node_modules/.pnpm/@jest+transform@27.2.1/node_modules/@jest/transform/build/ScriptTransformer.js:815:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.331 s
Ran all test suites.
```

```ts
module.exports = {
    preset: "ts-jest",
    globals: {
        "ts-jest": {
            babelConfig: true,
            diagnostics: false,
        },
    },
    testEnvironment: "jsdom",
    moduleFileExtensions: ["js", "jsx", "json", "vue", "ts", "tsx"],
    transform: {
        "^.+\\js$": "ts-jest",
        "^.+\\.vue$": "vue-jest",
        ".+\\.(css|styl|less|sass|scss|jpg|jpeg|png|svg|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|avif)$":
            "jest-transform-stub",
        "^.+\\.jsx?$": "ts-jest",
        "^.+\\.tsx?$": "ts-jest",
    },
    transformIgnorePatterns: ["/node_modules/"],
    // support the same @ -> src alias mapping in source code
    moduleNameMapper: {
        "^@/(.*)$": "<rootDir>/src/$1",
    },
    // serializer for snapshots
    snapshotSerializers: ["jest-serializer-vue"],
    testMatch: [
        "**/tests/unit/**/*.spec.[jt]s?(x)",
        "**/__tests__/*.[jt]s?(x)",
    ],
    // https://github.com/facebook/jest/issues/6766
    testURL: "http://localhost/",
    watchPlugins: [
        require.resolve("jest-watch-typeahead/filename"),
        require.resolve("jest-watch-typeahead/testname"),
    ],
};
```

**Comment by cexbrayat** [comment]
Hi @lampewebdev 

This is not an error with VTU but with vue-jest. 😉

With this error, I suppose you're using jest v27. If that's the case you need to replace `vue-jest` with `@vue/vue3-jest`, a new package we just released to support jest 27. You can generate a new project with Vue CLI v5.0.0-beta.4 to see how to set it up, but that should be straightforward.

**Comment by lampewebdev** [comment]
Thanks for the quick answer.
And yeah this works :)
